version: "3.7"

services:
  database_ignite:
    image: postgres # como o postgres é uma imagem oficial do docker, ou seja, já está criada, apenas apontamos para ela. Diferente do nosso app
    container_name: database_ignite
    restart: always
    ports:
      - 5432:5432 # Se na maquina local for chamada a porta 5432 queremos que reflita no container de porta 5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=database_ignite
      - POSTGRES_DB=rentx
    volumes:
      - pgdata:/data/postgres
  app:
    build: . # mesmo que rodar docker build -t rentx .
    container_name: rentx # nome do container
    restart: always
    ports: 
      - 3333:3333 # porta do projeto e do container
    volumes:
      - .:/usr/app # - {o que será passado para o diretorio(no caso: tudo)}:{diretorio}
    links:
      - database_ignite
    depends_on:
      - database_ignite
volumes:
  pgdata:
    driver: local